services:
  smartix-app:
    image: modiconme/smartix:latest
    container_name: smartix
    ports:
      - "8080:8080"
    networks:
      - stock-app-network
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_URL=${POSTGRES_URL}"
      - "JWT_SECRET=${JWT_SECRET}"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - stock-app-network
    restart: unless-stopped

networks:
  stock-app-network:
    driver: bridge
