server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs

spring:
  datasource:
    username: ${POSTGRES_USER}
    url: ${POSTGRES_URL}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  jackson:
    deserialization:
      unwrap_root_value: true

jwt:
  sign-key: ${JWT_SECRET}
  token-prefix: Token
  access-valid-time: 1
  issuer: Smartix