server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  security:
  user:
    name: spring
    password: spring

jwt:
  sign-key: secretsecretsecretsecretsecretsecret
  token-prefix: Token
  access-valid-time: 1
  issuer: Smartix
