name: CI

on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Push to docker hub
        run: ./build.sh modiconme ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: 'Run tests with JaCoCo'
        shell: bash
        run: |
          ./gradlew --version
          ./gradlew --scan --no-parallel --stacktrace --warning-mode=all jacocoReport

      - uses: codecov/codecov-action@v1
